package tempest.sql;

import java.util.Enumeration;
import java.util.Hashtable;

public class Keyword {
    public static final int ABSOLUTE = 1000;
    public static final int ACTION = 1001;
    public static final int ADD = 1002;
    public static final int ADMIN = 1003;
    public static final int AFTER = 1004;
    public static final int AGGREGATE = 1005;
    public static final int ALIAS = 1006;
    public static final int ALL = 1007;
    public static final int ALLOCATE = 1008;
    public static final int ALTER = 1009;
    public static final int AND = 1010;
    public static final int ANY = 1011;
    public static final int ARE = 1012;
    public static final int ARRAY = 1013;
    public static final int AS = 1014;
    public static final int ASC = 1015;
    public static final int ASSERTION = 1016;
    public static final int AT = 1017;
    public static final int AUTHORIZATION = 1018;

    public static final int BEFORE = 1019;
    public static final int BEGIN = 1020;
    public static final int BINARY = 1021;
    public static final int BIT = 1022;
    public static final int BLOB = 1023;
    public static final int BOOLEAN = 1024;
    public static final int BOTH = 1025;
    public static final int BREADTH = 1026;
    public static final int BY = 1027;

    public static final int CALL = 1028;
    public static final int CASCADE = 1029;
    public static final int CASCADED = 1030;
    public static final int CASE = 1031;
    public static final int CAST = 1032;
    public static final int CATALOG = 1033;
    public static final int CHAR = 1034;
    public static final int CHARACTER = 1035;
    public static final int CHECK = 1036;
    public static final int CLASS = 1037;
    public static final int CLOB = 1038;
    public static final int CLOSE = 1039;
    public static final int COLLATE = 1040;
    public static final int COLLATION = 1041;
    public static final int COLUMN = 1042;
    public static final int COMMIT = 1043;
    public static final int COMPLETION = 1044;
    public static final int CONDITION = 1045;
    public static final int CONNECT = 1046;
    public static final int CONNECTION = 1047;
    public static final int CONSTRAINT = 1048;
    public static final int CONSTRAINTS = 1049;
    public static final int CONSTRUCTOR = 1050;
    public static final int CONTAINS = 1051;
    public static final int CONTINUE = 1052;
    public static final int CORRESPONDING = 1053;
    public static final int CREATE = 1054;
    public static final int CROSS = 1055;
    public static final int CUBE = 1056;
    public static final int CURRENT = 1057;
    public static final int CURRENT_DATE = 1058;
    public static final int CURRENT_PATH = 1059;
    public static final int CURRENT_ROLE = 1060;
    public static final int CURRENT_TIME = 1061;
    public static final int CURRENT_TIMESTAMP = 1062;
    public static final int CURRENT_USER = 1063;
    public static final int CURSOR = 1064;
    public static final int CYCLE = 1065;

    public static final int DATA = 1066;
    public static final int DATALINK = 1067;
    public static final int DATE = 1068;
    public static final int DAY = 1069;
    public static final int DEALLOCATE = 1070;
    public static final int DEC = 1071;
    public static final int DECIMAL = 1072;
    public static final int DECLARE = 1073;
    public static final int DEFAULT = 1074;
    public static final int DEFERRABLE = 1075;
    public static final int DELETE = 1076;
    public static final int DEPTH = 1077;
    public static final int DEREF = 1078;
    public static final int DESC = 1079;
    public static final int DESCRIPTOR = 1080;
    public static final int DIAGNOSTICS = 1081;
    public static final int DICTIONARY = 1082;
    public static final int DISCONNECT = 1083;
    public static final int DISTINCT = 10835;
    public static final int DO = 1084;
    public static final int DOMAIN = 1085;
    public static final int DOUBLE = 1086;
    public static final int DROP = 1087;

    public static final int END_EXEC = 1088;
    public static final int EQUALS = 1089;
    public static final int ESCAPE = 1090;
    public static final int EXCEPT = 1091;
    public static final int EXCEPTION = 1092;
    public static final int EXECUTE = 1093;
    public static final int EXIT = 1094;
    public static final int EXPAND = 1095;
    public static final int EXPANDING = 1096;

    public static final int FALSE = 1097;
    public static final int FIRST = 1098;
    public static final int FLOAT = 1099;
    public static final int FOR = 1100;
    public static final int FOREIGN = 1101;
    public static final int FREE = 1102;
    public static final int FROM = 1103;
    public static final int FUNCTION = 1104;

    public static final int GENERAL = 1105;
    public static final int GET = 1106;
    public static final int GLOBAL = 1107;
    public static final int GOTO = 1108;
    public static final int GRANT = 11085;
    public static final int GROUP = 1109;
    public static final int GROUPING = 1110;

    public static final int HANDLER = 1111;
    public static final int HASH = 1112;
    public static final int HAVING = 11121;
    public static final int HOUR = 1113;

    public static final int IDENTITY = 1114;
    public static final int IF = 1115;
    public static final int IGNORE = 1116;
    public static final int IMMEDIATE = 1117;
    public static final int IN = 1118;
    public static final int INDICATOR = 1119;
    public static final int INITIALIZE = 1120;
    public static final int INITIALLY = 1121;
    public static final int INNER = 1122;
    public static final int INOUT = 1123;
    public static final int INPUT = 1124;
    public static final int INSERT = 1125;
    public static final int INT = 1126;
    public static final int INTEGER = 1127;
    public static final int INTERSECT = 1128;
    public static final int INTERVAL = 1129;
    public static final int INTO = 1130;
    public static final int IS = 1131;
    public static final int ISOLATION = 1132;
    public static final int ITERATE = 1133;

    public static final int JOIN = 1134;

    public static final int KEY = 1135;

    public static final int LANGUAGE = 1136;
    public static final int LARGE = 1137;
    public static final int LAST = 1138;
    public static final int LATERAL = 1139;
    public static final int LEADING = 1140;
    public static final int LEAVE = 1141;
    public static final int LEFT = 1142;
    public static final int LESS = 1143;
    public static final int LEVEL = 1144;
    public static final int LIKE = 1145;
    public static final int LIMIT = 1146;
    public static final int LOCAL = 1147;
    public static final int LOCALTIME = 1148;
    public static final int LOCALTIMESTAMP = 1149;
    public static final int LOCATOR = 1150;
    public static final int LOOP = 1151;

    public static final int MATCH = 1152;
    public static final int MEETS = 1153;
    public static final int MINUTE = 1154;
    public static final int MODIFIES = 1155;
    public static final int MODIFY = 1156;
    public static final int MODULE = 1157;
    public static final int MONTH = 1158;

    public static final int NAMES = 1159;
    public static final int NATIONAL = 1160;
    public static final int NATURAL = 1161;
    public static final int NCHAR = 1162;
    public static final int NCLOB = 1163;
    public static final int NEW = 1164;
    public static final int NEXT = 1165;
    public static final int NO = 1166;
    public static final int NONE = 1167;
    public static final int NORMALIZE = 1168;
    public static final int NOT = 1169;
    public static final int NULL = 1170;
    public static final int NUMERIC = 1171;

    public static final int OBJECT = 1172;
    public static final int OF = 1173;
    public static final int OFF = 1174;
    public static final int OLD = 1175;
    public static final int ON = 1176;
    public static final int ONLY = 1177;
    public static final int OPEN = 1178;
    public static final int OPERATION = 1179;
    public static final int OPTION = 1180;
    public static final int OR = 1181;
    public static final int ORDER = 1182;
    public static final int ORDINALITY = 1183;
    public static final int OUT = 1184;
    public static final int OUTER = 1185;
    public static final int OUTPUT = 1185;

    public static final int PAD = 1186;
    public static final int PARAMETER = 1187;
    public static final int PARAMETERS = 1188;
    public static final int PARTIAL = 1189;
    public static final int PATH = 1190;
    public static final int PERIOD = 1191;
    public static final int POSTFIX = 1192;
    public static final int PRECEDES = 1193;
    public static final int PRECISION = 1194;
    public static final int PREFIX = 1195;
    public static final int PREORDER = 1196;
    public static final int PREPARE = 1197;
    public static final int PRESERVE = 1198;
    public static final int PRIMARY = 1199;
    public static final int PRIOR = 1200;
    public static final int PRIVILEGES = 1201;
    public static final int PROCEDURE = 1202;
    public static final int PUBLIC = 1203;

    public static final int READ = 1204;
    public static final int READS = 1205;
    public static final int REAL = 1206;
    public static final int RECURSIVE = 1207;
    public static final int REDO = 1208;
    public static final int REF = 1209;
    public static final int REFERENCES = 1210;
    public static final int REFERENCING = 1211;
    public static final int RELATIVE = 1212;
    public static final int REPEAT = 1213;
    public static final int RESIGNAL = 1214;
    public static final int RESTRICT = 1215;
    public static final int RESULT = 1216;
    public static final int RETURN = 1217;
    public static final int RETURNS = 1218;
    public static final int REVOKE = 1219;
    public static final int RIGHT = 1220;
    public static final int ROLE = 1221;
    public static final int ROLLBACK = 1222;
    public static final int ROLLUP = 1223;
    public static final int ROUTINE = 1224;
    public static final int ROW = 1225;
    public static final int ROWS = 1226;

    public static final int SAVEPOINT = 1227;
    public static final int SCHEMA = 1228;
    public static final int SCROLL = 1229;
    public static final int SEARCH = 1230;
    public static final int SECOND = 1231;
    public static final int SECTION = 1232;
    public static final int SELECT = 1233;
    public static final int SEQUENCE = 1234;
    public static final int SESSION = 1235;
    public static final int SESSION_USER = 1236;
    public static final int SET = 1237;
    public static final int SETS = 1238;
    public static final int SIGNAL = 1239;
    public static final int SIZE = 1240;
    public static final int SMALLINT = 1241;
    public static final int SPECIFIC = 1242;
    public static final int SPECIFICTYPE = 1243;
    public static final int SQL = 1244;
    public static final int SQLEXCEPTION = 1245;
    public static final int SQLSTATE = 1246;
    public static final int SQLWARNING = 1247;
    public static final int START = 1248;
    public static final int STATE = 1249;
    public static final int STATIC = 1250;
    public static final int STRUCTURE = 1251;
    public static final int SUCCEEDS = 1252;
    public static final int SUM = 1253;
    public static final int SYSTEM_USER = 1254;

    public static final int TABLE = 1255;
    public static final int TEMPORARY = 1256;
    public static final int TERMINATE = 1257;
    public static final int THAN = 1258;
    public static final int THEN = 1259;
    public static final int TIME = 1260;
    public static final int TIMESTAMP = 1261;
    public static final int TIMEZONE_HOUR = 1262;
    public static final int TIMEZONE_MINUTE = 1263;
    public static final int TO = 1264;
    public static final int TRAILING = 1265;
    public static final int TRANSACTION = 1266;
    public static final int TRANSLATION = 1267;
    public static final int TREAT = 1268;
    public static final int TRIGGER = 1269;
    public static final int TRUE = 1270;

    public static final int UNDER = 1271;
    public static final int UNDO = 1272;
    public static final int UNION = 1273;
    public static final int UNIQUE = 1274;
    public static final int UNKNOWN = 1275;
    public static final int UNTIL = 1276;
    public static final int UPDATE = 1277;
    public static final int USAGE = 1278;
    public static final int USER = 1279;
    public static final int USING = 1280;

    public static final int VALUE = 1281;
    public static final int VALUES = 1282;
    public static final int VARCHAR = 12825;
    public static final int VARIABLE = 1283;
    public static final int VARYING = 1284;
    public static final int VIEW = 1285;

    public static final int WHEN = 1286;
    public static final int WHENEVER = 1287;
    public static final int WHERE = 1288;
    public static final int WHILE = 1289;
    public static final int WITH = 1290;
    public static final int WRITE = 1291;

    public static final int YEAR = 1292;

    public static final int ZONE = 1293;

    private static Hashtable<String, Integer> keywords = new Hashtable<String, Integer>();
    private static Hashtable<Integer, String> ints = new Hashtable<Integer, String>();

    static {
        keywords.put("ABSOLUTE", ABSOLUTE);
        keywords.put("ACTION", ACTION);
        keywords.put("ADD", ADD);
        keywords.put("ADMIN", ADMIN);
        keywords.put("AFTER", AFTER);
        keywords.put("AGGREGATE", AGGREGATE);
        keywords.put("ALIAS", ALIAS);
        keywords.put("ALL", ALL);
        keywords.put("ALLOCATE", ALLOCATE);
        keywords.put("ALTER", ALTER);
        keywords.put("AND", AND);
        keywords.put("ANY", ANY);
        keywords.put("ARE", ARE);
        keywords.put("ARRAY", ARRAY);
        keywords.put("AS", AS);
        keywords.put("ASC", ASC);
        keywords.put("ASSERTION", ASSERTION);
        keywords.put("AT", AT);
        keywords.put("AUTHORIZATION", AUTHORIZATION);

        keywords.put("BEFORE", BEFORE);
        keywords.put("BEGIN", BEGIN);
        keywords.put("BINARY", BINARY);
        keywords.put("BIT", BIT);
        keywords.put("BLOB", BLOB);
        keywords.put("BOOLEAN", BOOLEAN);
        keywords.put("BOTH", BOTH);
        keywords.put("BREADTH", BREADTH);
        keywords.put("BY", BY);

        keywords.put("CALL", CALL);
        keywords.put("CASCADE", CASCADE);
        keywords.put("CASCADED", CASCADED);
        keywords.put("CASE", CASE);
        keywords.put("CAST", CAST);
        keywords.put("CATALOG", CATALOG);
        keywords.put("CHAR", CHAR);
        keywords.put("CHARACTER", CHARACTER);
        keywords.put("CHECK", CHECK);
        keywords.put("CLASS", CLASS);
        keywords.put("CLOB", CLOB);
        keywords.put("CLOSE", CLOSE);
        keywords.put("COLLATE", COLLATE);
        keywords.put("COLLATION", COLLATION);
        keywords.put("COLUMN", COLUMN);
        keywords.put("COMMIT", COMMIT);
        keywords.put("COMPLETION", COMPLETION);
        keywords.put("CONDITION", CONDITION);
        keywords.put("CONNECT", CONNECT);
        keywords.put("CONNECTION", CONNECTION);
        keywords.put("CONSTRAINT", CONSTRAINT);
        keywords.put("CONSTRAINTS", CONSTRAINTS);
        keywords.put("CONSTRUCTOR", CONSTRUCTOR);
        keywords.put("CONTAINS", CONTAINS);
        keywords.put("CONTINUE", CONTINUE);
        keywords.put("CORRESPONDING", CORRESPONDING);
        keywords.put("CREATE", CREATE);
        keywords.put("CROSS", CROSS);
        keywords.put("CUBE", CUBE);
        keywords.put("CURRENT", CURRENT);
        keywords.put("CURRENT_DATE", CURRENT_DATE);
        keywords.put("CURRENT_PATH", CURRENT_PATH);
        keywords.put("CURRENT_ROLE", CURRENT_ROLE);
        keywords.put("CURRENT_TIME", CURRENT_TIME);
        keywords.put("CURRENT_TIMESTAMP", CURRENT_TIMESTAMP);
        keywords.put("CURRENT_USER", CURRENT_USER);
        keywords.put("CURSOR", CURSOR);
        keywords.put("CYCLE", CYCLE);

        keywords.put("DATA", DATA);
        keywords.put("DATALINK", DATALINK);
        keywords.put("DATE", DATE);
        //keywords.put("DATETIME", DATETIME);
        keywords.put("DAY", DAY);
        keywords.put("DEALLOCATE", DEALLOCATE);
        keywords.put("DEC", DEC);
        keywords.put("DECIMAL", DECIMAL);
        keywords.put("DECLARE", DECLARE);
        keywords.put("DEFAULT", DEFAULT);
        keywords.put("DEFERRABLE", DEFERRABLE);
        keywords.put("DELETE", DELETE);
        keywords.put("DEPTH", DEPTH);
        keywords.put("DEREF", DEREF);
        keywords.put("DESC", DESC);
        keywords.put("DESCRIPTOR", DESCRIPTOR);
        keywords.put("DIAGNOSTICS", DIAGNOSTICS);
        keywords.put("DICTIONARY", DICTIONARY);
        keywords.put("DISCONNECT", DISCONNECT);
        keywords.put("DISTINCT", DISTINCT);
        keywords.put("DO", DO);
        keywords.put("DOMAIN", DOMAIN);
        keywords.put("DOUBLE", DOUBLE);
        keywords.put("DROP", DROP);

        keywords.put("END_EXEC", END_EXEC);
        keywords.put("EQUALS", EQUALS);
        keywords.put("ESCAPE", ESCAPE);
        keywords.put("EXCEPT", EXCEPT);
        keywords.put("EXCEPTION", EXCEPTION);
        keywords.put("EXECUTE", EXECUTE);
        keywords.put("EXIT", EXIT);
        keywords.put("EXPAND", EXPAND);
        keywords.put("EXPANDING", EXPANDING);

        keywords.put("FALSE", FALSE);
        keywords.put("FIRST", FIRST);
        keywords.put("FLOAT", FLOAT);
        keywords.put("FOR", FOR);
        keywords.put("FOREIGN", FOREIGN);
        keywords.put("FREE", FREE);
        keywords.put("FROM", FROM);
        keywords.put("FUNCTION", FUNCTION);

        keywords.put("GENERAL", GENERAL);
        keywords.put("GET", GET);
        keywords.put("GLOBAL", GLOBAL);
        keywords.put("GOTO", GOTO);
        keywords.put("GRANT", GRANT);
        keywords.put("GROUP", GROUP);
        keywords.put("GROUPING", GROUPING);

        keywords.put("HANDLER", HANDLER);
        keywords.put("HASH", HASH);
        keywords.put("HAVING", HAVING);
        keywords.put("HOUR", HOUR);

        keywords.put("IDENTITY", IDENTITY);
        keywords.put("IF", IF);
        keywords.put("IGNORE", IGNORE);
        keywords.put("IMMEDIATE", IMMEDIATE);
        keywords.put("IN", IN);
        keywords.put("INDICATOR", INDICATOR);
        keywords.put("INITIALIZE", INITIALIZE);
        keywords.put("INITIALLY", INITIALLY);
        keywords.put("INNER", INNER);
        keywords.put("INOUT", INOUT);
        keywords.put("INPUT", INPUT);
        keywords.put("INSERT", INSERT);
        keywords.put("INT", INT);
        keywords.put("INTEGER", INTEGER);
        keywords.put("INTERSECT", INTERSECT);
        keywords.put("INTERVAL", INTERVAL);
        keywords.put("INTO", INTO);
        keywords.put("IS", IS);
        keywords.put("ISOLATION", ISOLATION);
        keywords.put("ITERATE", ITERATE);

        keywords.put("JOIN", JOIN);

        keywords.put("KEY", KEY);

        keywords.put("LANGUAGE", LANGUAGE);
        keywords.put("LARGE", LARGE);
        keywords.put("LAST", LAST);
        keywords.put("LATERAL", LATERAL);
        keywords.put("LEADING", LEADING);
        keywords.put("LEAVE", LEAVE);
        keywords.put("LEFT", LEFT);
        keywords.put("LESS", LESS);
        keywords.put("LEVEL", LEVEL);
        keywords.put("LIKE", LIKE);
        keywords.put("LIMIT", LIMIT);
        keywords.put("LOCAL", LOCAL);
        keywords.put("LOCALTIME", LOCALTIME);
        keywords.put("LOCALTIMESTAMP", LOCALTIMESTAMP);
        keywords.put("LOCATOR", LOCATOR);
        keywords.put("LOOP", LOOP);

        keywords.put("MATCH", MATCH);
        keywords.put("MEETS", MEETS);
        keywords.put("MINUTE", MINUTE);
        keywords.put("MODIFIES", MODIFIES);
        keywords.put("MODIFY", MODIFY);
        keywords.put("MODULE", MODULE);
        keywords.put("MONTH", MONTH);

        keywords.put("NAMES", NAMES);
        keywords.put("NATIONAL", NATIONAL);
        keywords.put("NATURAL", NATURAL);
        keywords.put("NCHAR", NCHAR);
        keywords.put("NCLOB", NCLOB);
        keywords.put("NEW", NEW);
        keywords.put("NEXT", NEXT);
        keywords.put("NO", NO);
        keywords.put("NONE", NONE);
        keywords.put("NORMALIZE", NORMALIZE);
        keywords.put("NOT", NOT);
        keywords.put("NULL", NULL);
        keywords.put("NUMERIC", NUMERIC);

        keywords.put("OBJECT", OBJECT);
        keywords.put("OF", OF);
        keywords.put("OFF", OFF);
        keywords.put("OLD", OLD);
        keywords.put("ON", ON);
        keywords.put("ONLY", ONLY);
        keywords.put("OPEN", OPEN);
        keywords.put("OPERATION", OPERATION);
        keywords.put("OPTION", OPTION);
        keywords.put("OR", OR);
        keywords.put("ORDER", ORDER);
        keywords.put("ORDINALITY", ORDINALITY);
        keywords.put("OUT", OUT);
        keywords.put("OUTER", OUTER);
        keywords.put("OUTPUT", OUTPUT);

        keywords.put("PAD", PAD);
        keywords.put("PARAMETER", PARAMETER);
        keywords.put("PARAMETERS", PARAMETERS);
        keywords.put("PARTIAL", PARTIAL);
        keywords.put("PATH", PATH);
        keywords.put("PERIOD", PERIOD);
        keywords.put("POSTFIX", POSTFIX);
        keywords.put("PRECEDES", PRECEDES);
        keywords.put("PRECISION", PRECISION);
        keywords.put("PREFIX", PREFIX);
        keywords.put("PREORDER", PREORDER);
        keywords.put("PREPARE", PREPARE);
        keywords.put("PRESERVE", PRESERVE);
        keywords.put("PRIMARY", PRIMARY);
        keywords.put("PRIOR", PRIOR);
        keywords.put("PRIVILEGES", PRIVILEGES);
        keywords.put("PROCEDURE", PROCEDURE);
        keywords.put("PUBLIC", PUBLIC);

        keywords.put("READ", READ);
        keywords.put("READS", READS);
        keywords.put("REAL", REAL);
        keywords.put("RECURSIVE", RECURSIVE);
        keywords.put("REDO", REDO);
        keywords.put("REF", REF);
        keywords.put("REFERENCES", REFERENCES);
        keywords.put("REFERENCING", REFERENCING);
        keywords.put("RELATIVE", RELATIVE);
        keywords.put("REPEAT", REPEAT);
        keywords.put("RESIGNAL", RESIGNAL);
        keywords.put("RESTRICT", RESTRICT);
        keywords.put("RESULT", RESULT);
        keywords.put("RETURN", RETURN);
        keywords.put("RETURNS", RETURNS);
        keywords.put("REVOKE", REVOKE);
        keywords.put("RIGHT", RIGHT);
        keywords.put("ROLE", ROLE);
        keywords.put("ROLLBACK", ROLLBACK);
        keywords.put("ROLLUP", ROLLUP);
        keywords.put("ROUTINE", ROUTINE);
        keywords.put("ROW", ROW);
        keywords.put("ROWS", ROWS);

        keywords.put("SAVEPOINT", SAVEPOINT);
        keywords.put("SCHEMA", SCHEMA);
        keywords.put("SCROLL", SCROLL);
        keywords.put("SEARCH", SEARCH);
        keywords.put("SECOND", SECOND);
        keywords.put("SECTION", SECTION);
        keywords.put("SELECT", SELECT);
        keywords.put("SEQUENCE", SEQUENCE);
        keywords.put("SESSION", SESSION);
        keywords.put("SESSION_USER", SESSION_USER);
        keywords.put("SET", SET);
        keywords.put("SETS", SETS);
        keywords.put("SIGNAL", SIGNAL);
        keywords.put("SIZE", SIZE);
        keywords.put("SMALLINT", SMALLINT);
        keywords.put("SPECIFIC", SPECIFIC);
        keywords.put("SPECIFICTYPE", SPECIFICTYPE);
        keywords.put("SQL", SQL);
        keywords.put("SQLEXCEPTION", SQLEXCEPTION);
        keywords.put("SQLSTATE", SQLSTATE);
        keywords.put("SQLWARNING", SQLWARNING);
        keywords.put("START", START);
        keywords.put("STATE", STATE);
        keywords.put("STATIC", STATIC);
        keywords.put("STRUCTURE", STRUCTURE);
        keywords.put("SUCCEEDS", SUCCEEDS);
        keywords.put("SUM", SUM);
        keywords.put("SYSTEM_USER", SYSTEM_USER);

        keywords.put("TABLE", TABLE);
        keywords.put("TEMPORARY", TEMPORARY);
        keywords.put("TERMINATE", TERMINATE);
        keywords.put("THAN", THAN);
        keywords.put("THEN", THEN);
        keywords.put("TIME", TIME);
        keywords.put("TIMESTAMP", TIMESTAMP);
        keywords.put("TIMEZONE_HOUR", TIMEZONE_HOUR);
        keywords.put("TIMEZONE_MINUTE", TIMEZONE_MINUTE);
        keywords.put("TO", TO);
        keywords.put("TRAILING", TRAILING);
        keywords.put("TRANSACTION", TRANSACTION);
        keywords.put("TRANSLATION", TRANSLATION);
        keywords.put("TREAT", TREAT);
        keywords.put("TRIGGER", TRIGGER);
        keywords.put("TRUE", TRUE);

        keywords.put("UNDER", UNDER);
        keywords.put("UNDO", UNDO);
        keywords.put("UNION", UNION);
        keywords.put("UNIQUE", UNIQUE);
        keywords.put("UNKNOWN", UNKNOWN);
        keywords.put("UNTIL", UNTIL);
        keywords.put("UPDATE", UPDATE);
        keywords.put("USAGE", USAGE);
        keywords.put("USER", USER);
        keywords.put("USING", USING);

        keywords.put("VALUE", VALUE);
        keywords.put("VALUES", VALUES);
        keywords.put("VARCHAR", VARCHAR);
        keywords.put("VARIABLE", VARIABLE);
        keywords.put("VARYING", VARYING);
        keywords.put("VIEW", VIEW);

        keywords.put("WHEN", WHEN);
        keywords.put("WHENEVER", WHENEVER);
        keywords.put("WHERE", WHERE);
        keywords.put("WHILE", WHILE);
        keywords.put("WITH", WITH);
        keywords.put("WRITE", WRITE);

        keywords.put("YEAR", YEAR);

        keywords.put("ZONE", ZONE);

        Enumeration<String> en = keywords.keys();
        while(en.hasMoreElements()) {
            String kw = en.nextElement();
            ints.put(keywords.get(kw), kw);
        }
    }

    public Keyword() {}

    public static int getInt(String name) {
        if(name == null) return -1;
        var i = keywords.get(name.toUpperCase());
        if(i == null) return -1;
        return i;
    }

    public static String getString(int n) {
        String s = ints.get(n);
        if(s == null) return "-";
        return s;
    }

}